version: '3'
services:
  logexp-web:
    image: logexp-img
    network_mode: host
    build: ./
    depends_on:
      - logexp-db
    ports:
      - "5000:5000"

  logexp-db:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_DB: logexp_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/
    restart: unless-stopped

volumes:
  db-data:

