# filename: ansible/playbooks/deploy-logexp.yml
---
# Deploy LogExp to keepâ€‘0001 (or any host in the logexp group)

- name: Deploy LogExp application
  hosts: logexp
  become: true
  gather_facts: false

  roles:
    - pi_prep
    - logexp_deploy
