# filename: ansible/playbooks/deploy-logexp.yml
---
# Deploy LogExp to Beamriderâ€‘0002 (or any host in the logexp group)

- name: Deploy LogExp application
  hosts: logexp
  become: true
  gather_facts: false

  roles:
    - logexp_deploy
